// Verification script for Resend domain authentication (SPF/DKIM/DMARC).
// Run: npx tsx scripts/verify-domain-auth.ts
//
// This script is READ-ONLY — it does NOT send email, does NOT modify DB,
// does NOT modify Render config, and does NOT touch any booking/provisioning
// logic. It only checks DNS resolution of TXT records expected for the
// currently configured sending domain.

import * as http from "node:http";
import * as dns from "node:dns/promises";
import * as fs from "node:fs";
import * as path from "node:path";

// Resolve the sending domain from the process environment, matching the
// pattern used everywhere in the codebase: EMAIL_FROM = "Scheduler <domain>"
function extractSendingDomain(): string | null {
  const envFrom = process.env.EMAIL_FROM;
  if (!envFrom) return null;
  // Format: "Scheduler <domain>" or "Name <email>"
  const match = envFrom.match(/<(.+)>/);
  return match ? match[1].trim() : null;
}

// Check that a TXT record exists and contains the expected value.
// For SPF: must contain the domain's mechanism (e.g. include:_spf.resend.com or ~all)
// For DKIM: must contain the selector string (e.g. "google" or "k1")
// For DMARC: must contain "v=DMARC1" and the policy p=
async function checkTxtRecord(
  domain: string,
  recordLabel: string,
  expectedSubstring: string
): Promise<{ present: boolean; found: string | null }> {
  try {
    // Collect all TXT answers for the domain
    const answers = await dns.resolveTxt(domain);
    for (const record of answers) {
      // Each record is a Buffer; join the parts
      const txt = record.join(" ");
      if (txt.includes(expectedSubstring)) {
        return { present: true, found: txt };
      }
    }
    return { present: false, found: null };
  } catch (err) {
    // If DNS resolution fails entirely (e.g. no such domain, no network),
    // report not-present rather than crashing.
    return { present: false, found: null };
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const domain = extractSendingDomain();
  if (!domain) {
    console.error(
      "ERROR: Could not extract a sending domain from EMAIL_FROM.\n" +
        "Expected format: \"Scheduler <domain>\" (e.g. \"Scheduler <notifications@eureka-ent.org>\")\n" +
        "Set EMAIL_FROM in your environment and re-run."
    );
    process.exit(1);
  }

  console.log(`Checking domain authentication for: ${domain}\n`);

  let allPass = true;

  // 1. SPF check
  // Resend's SPF typically includes "v=spf1 include:_spf.resend.com ~all"
  // but the exact record is generated by Resend after domain verification.
  // We just check for a typical SPF TXT record containing "include:_spf.resend.com" or "~all".
  const spf = await checkTxtRecord(domain, "SPF", "include:_spf.resend.com");
  const spfLabel = spf.present ? "PASS" : "FAIL/MISSING";
  console.log(`[SPF] ${spfLabel} — found: ${spf.found ?? "no matching TXT record"}`);
  if (!spf.present) allPass = false;

  // 2. DKIM check
  // Resend typically publishes a DKIM CNAME or TXT with a selector like "k1" or "google".
  // We check for a generic DKIM indicator. The exact selector is Resend-specific.
  const dkim = await checkTxtRecord(domain, "DKIM", "google");
  // Note: DKIM in Resend uses CNAME typically, but a TXT check is our best effort here.
  const dkimLabel = dkim.present ? "PASS" : "FAIL/MISSING (DKIM is usually a CNAME in Resend)";
  console.log(`[DKIM] ${dkimLabel} — found: ${dkim.found ?? "no matching TXT record"}`);
  if (!dkim.present) allPass = false;

  // 3. DMARC check
  // We look for a DMARC TXT record at _dmarc.<domain>
  const dmarcDomain = `_dmarc.${domain}`;
  const dmarc = await checkTxtRecord(dmarcDomain, "DMARC", "v=DMARC1");
  const dmarcLabel = dmarc.present ? "PASS" : "FAIL/MISSING";
  console.log(`[DMARC] ${dmarcLabel} — domain: ${dmarcDomain}, found: ${dmarc.found ?? "no matching TXT record"}`);
  if (!dmarc.present) allPass = false;

  // Summary
  console.log("\n---");
  if (allPass) {
    console.log("All checks PASSED — domain authentication appears configured.");
    process.exit(0);
  } else {
    console.log("One or more checks FAILED — domain authentication is NOT yet configured.");
    console.log("\nNext steps (manual):");
    console.log("1. Add a custom domain in Resend dashboard → Domains → Add custom domain");
    console.log("2. Follow Resend's instructions to verify the domain (add TXT record to DNS)");
    console.log("3. After verification, Resend will generate SPF/DKIM/CNAME records");
    console.log("4. Add those records to your DNS provider/registrar");
    console.log("5. Optionally add a DMARC TXT record at _dmarc.<yourdomain> with p=none first");
    console.log("6. Update .env EMAIL_FROM to match the verified domain, e.g.:");
    console.log('   EMAIL_FROM="Scheduler <notifications@mail.eureka-ent.org>"');
    process.exit(1);
  }
}

// Run main, swallow any unexpected errors so the script is truly read-only.
main().catch((e) => {
  console.error("Unexpected error in verify-domain-auth:", e);
  process.exit(1);
});